In [11]:
#importing libs
import torch
import torch.nn as nn

In [12]:
# create model class
# basically a single nural
class Model(nn.Module):
# "nn.module" is inherited here
  def __init__(self, num_features):
# constructor, num-features = no of rows
    super().__init__()
    # super keyword is used to invoke the constructor of nn.moduls class
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [13]:
# create dataset
features = torch.rand(10,5)

In [14]:
# create model
model = Model(features.shape[1])

In [15]:
# call model for forward pass
# "model.forward(features)" this also works but pytorch recommends to code us like this as given below
model(features)

tensor([[0.3922],
        [0.4529],
        [0.3973],
        [0.4463],
        [0.4757],
        [0.4458],
        [0.4321],
        [0.4295],
        [0.4526],
        [0.4048]], grad_fn=<SigmoidBackward0>)

the above output is the y_prid of the nural network

In [19]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.0872,  0.3995, -0.0900,  0.0425, -0.2710]], requires_grad=True)

In [20]:
# displaying models bias
model.linear.bias

Parameter containing:
tensor([-0.4044], requires_grad=True)

In [17]:
!pip install torchinfo

In [18]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00