In [1]:
#importing libs
import torch
import torch.nn as nn

In [18]:
# create model class
# basically a single nural
class Model(nn.Module):
# "nn.module" is inherited here
  def __init__(self, num_features):
# constructor, num-features = no of rows
    super().__init__()
    # super keyword is used to invoke the constructor of nn.moduls class
    self.linear = nn.Linear(num_features,3)
      #first layer where there 5 features are given as input
    self.relu = nn.ReLU()
      # relu is used as bias
    self.linear2 = nn.Linear(3,1)
      # here there is three layers in hidden layer, and three inputs from 1st layer and 1 y_pred is given as output
    self.sigmoid = nn.Sigmoid()
      # sigmoid is used as bias

  def forward(self,features):
    out = self.linear(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [19]:
# create dataset
features = torch.rand(10,5)

In [20]:
# create model
model = Model(features.shape[1])


In [22]:
# call model for forward pass
# "model.forward(features)" this also works but pytorch recommends to code us like this as given below
model(features)

tensor([[0.4331],
        [0.4185],
        [0.4395],
        [0.4573],
        [0.4645],
        [0.4429],
        [0.4195],
        [0.4328],
        [0.4650],
        [0.4287]], grad_fn=<SigmoidBackward0>)

In [23]:
# weights of first layer i.e
model.linear.weight

Parameter containing:
tensor([[ 0.0452, -0.2387, -0.1856,  0.0382, -0.1442],
        [-0.1962,  0.0706, -0.2551,  0.3936,  0.1439],
        [-0.1895,  0.3492, -0.1482,  0.2129, -0.0413]], requires_grad=True)

In [24]:
# weights of the second layer
model.linear2.weight

Parameter containing:
tensor([[0.2737, 0.0665, 0.5667]], requires_grad=True)

In [25]:
# ReLU bias of first layer
model.linear.bias

Parameter containing:
tensor([-0.2252, -0.1955,  0.4299], requires_grad=True)

In [26]:
# sigmoid bias of hidden layer
model.linear2.bias

Parameter containing:
tensor([-0.5469], requires_grad=True)

In [28]:
!pip install torchinfo

In [29]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00