In [65]:
!pip install nltk

In [66]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter
import nltk
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize

In [67]:
document = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [68]:
#Tokenization
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [69]:
#tokenize
tokens = word_tokenize(document.lower())

In [70]:
# built dictionary

vocab = {'<unk>':0}
# 'counter' is a builtin function that stores all the unique words in a dictionary and also tell us how many times does this word occured in the data
# this for loop adds every word unique words in vocab variable and also adds indexes to it
for token in Counter(tokens).keys():
  if token not in vocab:
    vocab[token] = len(vocab)
  # our vocablary is now completed

In [71]:
vocab

{'<unk>': 0,
 'about': 1,
 'the': 2,
 'program': 3,
 'what': 4,
 'is': 5,
 'course': 6,
 'fee': 7,
 'for': 8,
 'data': 9,
 'science': 10,
 'mentorship': 11,
 '(': 12,
 'dsmp': 13,
 '2023': 14,
 ')': 15,
 'follows': 16,
 'a': 17,
 'monthly': 18,
 'subscription': 19,
 'model': 20,
 'where': 21,
 'you': 22,
 'have': 23,
 'to': 24,
 'make': 25,
 'payments': 26,
 'of': 27,
 'rs': 28,
 '799/month': 29,
 '.': 30,
 'total': 31,
 'duration': 32,
 '?': 33,
 '7': 34,
 'months': 35,
 'so': 36,
 'becomes': 37,
 '799': 38,
 '*': 39,
 '=': 40,
 '5600': 41,
 'approx': 42,
 'syllabus': 43,
 'we': 44,
 'will': 45,
 'be': 46,
 'covering': 47,
 'following': 48,
 'modules': 49,
 ':': 50,
 'python': 51,
 'fundamentals': 52,
 'libraries': 53,
 'analysis': 54,
 'sql': 55,
 'maths': 56,
 'machine': 57,
 'learning': 58,
 'ml': 59,
 'algorithms': 60,
 'practical': 61,
 'mlops': 62,
 'case': 63,
 'studies': 64,
 'can': 65,
 'check': 66,
 'detailed': 67,
 'here': 68,
 '-': 69,
 'https': 70,
 '//learnwith.campusx.i

In [72]:
# extract sentences from data, basically divided the data into oneline sentences
input_sentences = document.split('\n')

In [73]:
input_sentences

['About the Program',
 'What is the course fee for  Data Science Mentorship Program (DSMP 2023)',
 'The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.',
 'What is the total duration of the course?',
 'The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)',
 'What is the syllabus of the mentorship program?',
 'We will be covering the following modules:',
 'Python Fundamentals',
 'Python libraries for Data Science',
 'Data Analysis',
 'SQL for Data Science',
 'Maths for Machine Learning',
 'ML Algorithms',
 'Practical ML',
 'MLOPs',
 'Case studies',
 'You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390',
 'Will Deep Learning and NLP be a part of this program?',
 'No, NLP and Deep Learning both are not a part of this program’s curriculum.',
 'What if I miss a live session? Will I get a recording 

In [74]:
# this particular function convert sentences into vectors
def text_to_indices(sentence, vocab):

  numerical_sentence = []

  for token in sentence:
    if token in vocab:
      numerical_sentence.append(vocab[token])
    else:
      numerical_sentence.append(vocab['<unk>'])

  return numerical_sentence

In [75]:
# now embed these english sentences/words in numbers with resprct to the keys present in vocablary
input_numerical_sentences = []

for sentence in input_sentences:
  input_numerical_sentences.append(text_to_indices(word_tokenize(sentence.lower()), vocab))


In [76]:
input_numerical_sentences

[[1, 2, 3],
 [4, 5, 2, 6, 7, 8, 9, 10, 11, 3, 12, 13, 14, 15],
 [2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18, 26, 27, 28, 29, 30],
 [4, 5, 2, 31, 32, 27, 2, 6, 33],
 [2,
  31,
  32,
  27,
  2,
  6,
  5,
  34,
  35,
  30,
  36,
  2,
  31,
  6,
  7,
  37,
  38,
  39,
  34,
  40,
  28,
  41,
  12,
  42,
  30,
  15],
 [4, 5, 2, 43, 27, 2, 11, 3, 33],
 [44, 45, 46, 47, 2, 48, 49, 50],
 [51, 52],
 [51, 53, 8, 9, 10],
 [9, 54],
 [55, 8, 9, 10],
 [56, 8, 57, 58],
 [59, 60],
 [61, 59],
 [62],
 [63, 64],
 [22, 65, 66, 2, 67, 43, 68, 69, 70, 50, 71],
 [45, 72, 58, 73, 74, 46, 17, 75, 27, 76, 3, 33],
 [77, 78, 74, 73, 72, 58, 79, 80, 81, 17, 75, 27, 76, 3, 82, 83, 84, 30],
 [4, 85, 86, 87, 17, 88, 89, 33, 45, 86, 90, 17, 91, 27, 2, 89, 33],
 [92,
  93,
  94,
  95,
  80,
  96,
  78,
  36,
  97,
  85,
  22,
  87,
  17,
  89,
  22,
  65,
  98,
  99,
  73,
  100,
  2,
  91,
  30],
 [21, 65, 86, 101, 2, 102, 103, 33],
 [104,
  76,
  105,
  106,
  24,
  107,
  108,
  109,
  108,
  110,
  111,
  27,

In [77]:
len(input_numerical_sentences)  # we have 78 sentences in total

78

In [78]:
# this loop makes the supervied data from the given sentences in data, ones refer notes
training_sequence = []
for sentence in input_numerical_sentences:

  for i in range(1, len(sentence)):
    training_sequence.append(sentence[:i+1])

In [79]:
len(training_sequence)

942

In [80]:
training_sequence[:5]

[[1, 2], [1, 2, 3], [4, 5], [4, 5, 2], [4, 5, 2, 6]]

In [81]:
# padding is needed here as the length of each vector is not equal so we have to bring all the vectors in same length

In [82]:
# first lets find the max length of vector and apply the padding accordlingly such that all the vextors come in one lenght i.e the max lenght
len_list = []

for sequence in training_sequence:
  len_list.append(len(sequence))

max_len = max(len_list)

In [83]:
max_len # now we have to bring all the vectors in the size of 62 by appling "pre padding" where zeros are added before the original vector

62

In [84]:
# generiting zeros and storing zeros in the training sequences

padded_training_sequence = []

for sequence in training_sequence:
  padded_training_sequence.append([0]*(max(len_list) - len(sequence)) + sequence)

In [85]:
padded_training_sequence[0]

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2]

In [86]:
len(padded_training_sequence[0])

62

In [87]:
len(padded_training_sequence[40])
# as we can see the size of every vector is same : 62

62

In [88]:
padded_training_sequence = torch.tensor(padded_training_sequence,dtype=torch.long)

In [89]:
padded_training_sequence

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   0,   4,   5],
        ...,
        [  0,   0,   0,  ..., 285, 176, 286],
        [  0,   0,   0,  ..., 176, 286, 287],
        [  0,   0,   0,  ..., 286, 287, 288]])

In [90]:
# input and output data has been generated. x = input coulmn, y = output coulmn
x = padded_training_sequence[:,:-1]
y = padded_training_sequence[:,-1]

In [91]:
x

tensor([[  0,   0,   0,  ...,   0,   0,   1],
        [  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   0,   0,   4],
        ...,
        [  0,   0,   0,  ...,   0, 285, 176],
        [  0,   0,   0,  ..., 285, 176, 286],
        [  0,   0,   0,  ..., 176, 286, 287]])

In [92]:
y

tensor([  2,   3,   5,   2,   6,   7,   8,   9,  10,  11,   3,  12,  13,  14,
         15,   6,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  18,  26,
         27,  28,  29,  30,   5,   2,  31,  32,  27,   2,   6,  33,  31,  32,
         27,   2,   6,   5,  34,  35,  30,  36,   2,  31,   6,   7,  37,  38,
         39,  34,  40,  28,  41,  12,  42,  30,  15,   5,   2,  43,  27,   2,
         11,   3,  33,  45,  46,  47,   2,  48,  49,  50,  52,  53,   8,   9,
         10,  54,   8,   9,  10,   8,  57,  58,  60,  59,  64,  65,  66,   2,
         67,  43,  68,  69,  70,  50,  71,  72,  58,  73,  74,  46,  17,  75,
         27,  76,   3,  33,  78,  74,  73,  72,  58,  79,  80,  81,  17,  75,
         27,  76,   3,  82,  83,  84,  30,  85,  86,  87,  17,  88,  89,  33,
         45,  86,  90,  17,  91,  27,   2,  89,  33,  93,  94,  95,  80,  96,
         78,  36,  97,  85,  22,  87,  17,  89,  22,  65,  98,  99,  73, 100,
          2,  91,  30,  65,  86, 101,   2, 102, 103,  33,  76, 1

In [93]:
# creating dataset class
class CustomDataset(Dataset):

  def __init__(self,x,y):
    super().__init__()
    self.x = x
    self.y = y

  def __len__(self):
    return self.x.shape[0]


  def __getitem__(self, idx):
    return self.x[idx], self.y[idx]

In [94]:
dataset = CustomDataset(x,y) # making object of dataset class

In [95]:
len(dataset) # to get the length of dataset

942

In [96]:
dataset[0] # to retrive a particular tensor from dataset, retrived below is the first item from dataset

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 tensor(2))

In [97]:
# lets make a dataloader and its object
dataloader = DataLoader(dataset, batch_size=32,shuffle=True)

In [98]:
# printed 32 items of each group
for input, output in dataloader:
  print(input,output)

tensor([[  0,   0,   0,  ...,   0,   0,  65],
        [  0,   0,   0,  ..., 248, 249, 147],
        [  0,   0,   0,  ...,   0,  22,  45],
        ...,
        [  0,   0,   0,  ...,  90,  17, 126],
        [  0,   0,   0,  ..., 188, 176, 189],
        [  0,   0,   0,  ...,   0, 210, 211]]) tensor([ 44, 246,  90,  13, 184, 174,  32,  52, 135,  18,  30,   3,  78, 134,
         22,  95, 151,  78,  17,   2,   2, 179, 106,   2,  38,  27, 147,  58,
        175, 127, 190, 212])
tensor([[  0,   0,   0,  ...,   2, 147, 150],
        [  0,   0,   0,  ...,  23, 219, 262],
        [  0,   0,   0,  ..., 131, 164,  28],
        ...,
        [  0,   0,   0,  ..., 186,  78,  22],
        [  0,   0,   0,  ..., 141, 144,  22],
        [  0,   0,   0,  ...,  81,  17,  75]]) tensor([142, 252,  41,  67, 194,  22,   2, 154,   2, 146,  23,  81,  16,  17,
        272,   2,  27, 262,  30, 250, 163,  23, 174, 131,  15,  86, 179,  24,
          2,  45, 155,  27])
tensor([[  0,   0,   0,  ...,  47,   2,  48],
    

In [99]:
# the data is furtheer embedded in the form of (32,61,100) where 32 - batches, 61-words, 100dimentions of data

In [100]:
from torch.nn.modules import Embedding
class LstmModel(nn.Module):
  def __init__(self,vocab_size,):
    super().__init__()
    self.embeddings = nn.Embedding(vocab_size,150)
    self.lstm = nn.LSTM(150,150,batch_first=True)
    self.fc = nn.Linear(150,vocab_size)

  def forward(self,x):
    embedded = self.embeddings(x)
    intermediate_hiddenstates, (final_hidden_state,final_cell_state) = self.lstm(embedded)
    output = self.fc(final_hidden_state.squeeze(0))
    return output

In [101]:
model = LstmModel(len(vocab))

In [102]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [103]:
model.to(device)

LstmModel(
  (embeddings): Embedding(289, 150)
  (lstm): LSTM(150, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=289, bias=True)
)

In [104]:
epochs = 50
learning_rate = 0.001

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr=learning_rate)

In [105]:
# training loop

for epochs in range(epochs):
  total_loss = 0

  for batch_x, batch_y in dataloader:
    batch_x = batch_x.to(device)
    batch_y = batch_y.to(device)
    optimizer.zero_grad()
    output = model(batch_x)
    loss = criterion(output,batch_y)
    loss.backward()
    optimizer.step()

    total_loss += loss.item()

  print(f"Epoch: {epochs+1}, Loss: {total_loss:.4f}")

Epoch: 1, Loss: 165.6029
Epoch: 2, Loss: 143.7870
Epoch: 3, Loss: 128.2033
Epoch: 4, Loss: 114.1466
Epoch: 5, Loss: 100.1383
Epoch: 6, Loss: 88.1179
Epoch: 7, Loss: 76.7839
Epoch: 8, Loss: 66.2918
Epoch: 9, Loss: 57.6223
Epoch: 10, Loss: 49.9199
Epoch: 11, Loss: 42.8053
Epoch: 12, Loss: 36.7349
Epoch: 13, Loss: 31.8317
Epoch: 14, Loss: 27.5774
Epoch: 15, Loss: 23.9982
Epoch: 16, Loss: 20.8423
Epoch: 17, Loss: 18.3439
Epoch: 18, Loss: 16.3153
Epoch: 19, Loss: 14.8292
Epoch: 20, Loss: 12.9168
Epoch: 21, Loss: 11.7470
Epoch: 22, Loss: 10.9115
Epoch: 23, Loss: 10.1266
Epoch: 24, Loss: 9.2140
Epoch: 25, Loss: 8.6011
Epoch: 26, Loss: 8.1786
Epoch: 27, Loss: 7.4928
Epoch: 28, Loss: 7.2191
Epoch: 29, Loss: 6.8968
Epoch: 30, Loss: 6.5179
Epoch: 31, Loss: 6.2935
Epoch: 32, Loss: 5.9602
Epoch: 33, Loss: 5.8984
Epoch: 34, Loss: 5.6119
Epoch: 35, Loss: 5.4157
Epoch: 36, Loss: 5.4891
Epoch: 37, Loss: 5.1620
Epoch: 38, Loss: 4.9583
Epoch: 39, Loss: 4.7486
Epoch: 40, Loss: 4.7040
Epoch: 41, Loss: 4.61

In [121]:
# prediction

def prediction(model, vocab, text):

  # tokenize
  tokenized_text = word_tokenize(text.lower())

  # text -> numerical indices
  numerical_text = text_to_indices(tokenized_text, vocab)

  # padding
  padded_text = torch.tensor([0] * (61 - len(numerical_text)) + numerical_text, dtype=torch.long).unsqueeze(0).to(device)

  # send to model
  output = model(padded_text)

  # predicted index
  value, index = torch.max(output, dim=1)

  # merge with text
  return text + " " + list(vocab.keys())[index]

In [122]:
prediction(model, vocab, "The course follows a monthly")

'The course follows a monthly subscription'

In [125]:
import time

num_tokens = 20
input_text = "the course"

for i in range(num_tokens):
  output_text = prediction(model, vocab, input_text)
  print(output_text)
  input_text = output_text
  time.sleep(0.5)

the course follows
the course follows a
the course follows a monthly
the course follows a monthly subscription
the course follows a monthly subscription model
the course follows a monthly subscription model where
the course follows a monthly subscription model where you
the course follows a monthly subscription model where you have
the course follows a monthly subscription model where you have to
the course follows a monthly subscription model where you have to make
the course follows a monthly subscription model where you have to make monthly
the course follows a monthly subscription model where you have to make monthly payments
the course follows a monthly subscription model where you have to make monthly payments of
the course follows a monthly subscription model where you have to make monthly payments of rs
the course follows a monthly subscription model where you have to make monthly payments of rs 799/month
the course follows a monthly subscription model where you have to make mo

In [126]:
dataloader1 = DataLoader(dataset, batch_size=32, shuffle=False)

In [127]:
# Function to calculate accuracy
def calculate_accuracy(model, dataloader, device):
    model.eval()  # Set the model to evaluation mode
    correct = 0
    total = 0

    with torch.no_grad():  # No need to compute gradients
        for batch_x, batch_y in dataloader1:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)

            # Get model predictions
            outputs = model(batch_x)

            # Get the predicted word indices
            _, predicted = torch.max(outputs, dim=1)

            # Compare with actual labels
            correct += (predicted == batch_y).sum().item()
            total += batch_y.size(0)

    accuracy = correct / total * 100
    return accuracy

# Compute accuracy
accuracy = calculate_accuracy(model, dataloader, device)
print(f"Model Accuracy: {accuracy:.2f}%")


Model Accuracy: 95.65%


In [106]:
# to understand embedding and lstm lets run them individually

x = nn.Embedding(289,100)
y = nn.LSTM(100,150,batch_first=True)
z = nn.Linear(150,289)

In [107]:
a = dataset[0][0].unsqueeze(0)

In [108]:
x(a)

tensor([[[-0.7579, -0.6061, -0.0801,  ..., -1.6865, -0.7195,  0.6628],
         [-0.7579, -0.6061, -0.0801,  ..., -1.6865, -0.7195,  0.6628],
         [-0.7579, -0.6061, -0.0801,  ..., -1.6865, -0.7195,  0.6628],
         ...,
         [-0.7579, -0.6061, -0.0801,  ..., -1.6865, -0.7195,  0.6628],
         [-0.7579, -0.6061, -0.0801,  ..., -1.6865, -0.7195,  0.6628],
         [-0.2115, -0.6199, -0.3712,  ...,  0.6099, -1.2127,  0.3655]]],
       grad_fn=<EmbeddingBackward0>)

In [109]:
x(a).shape

torch.Size([1, 61, 100])

In [110]:
# now sending this exact tensor into lstm
b = x(a)

In [111]:
len(y(b)) # there are two objects in this layer refer notes, 1st- intermediate hidden states, 2nd -

2

In [112]:
c ,d = y(b)

In [113]:
c.shape # hidden states

torch.Size([1, 61, 150])

In [114]:
len(d)  # again therere are two turpls here

2

In [115]:
e ,f = d

In [116]:
e.shape # this is a final time step

torch.Size([1, 1, 150])

In [117]:
f.shape # final time step

torch.Size([1, 1, 150])

In [118]:
z(f.squeeze(0)) # sending "f" in the fullyconnectedd layer
# the following out put is later used to measure the probablity of prediciting next word

tensor([[-6.7032e-02, -2.0732e-01, -1.6451e-02,  2.3284e-01,  8.7890e-02,
          1.3593e-01,  2.1766e-01,  1.8264e-01, -2.7594e-01, -6.1316e-02,
         -1.7608e-01, -1.5948e-01, -3.0069e-01, -1.9322e-01, -2.6795e-01,
          1.8509e-02, -3.4913e-02,  9.4916e-02,  1.2842e-01,  1.5831e-01,
         -1.4240e-02, -1.7467e-01, -6.5304e-02, -3.2130e-01,  1.4589e-02,
         -2.5110e-01, -1.1530e-01,  5.6970e-02, -7.8605e-02, -4.1996e-02,
         -6.8459e-03,  2.6511e-01,  5.9193e-03, -2.7906e-01,  1.8571e-01,
          4.8694e-01,  2.0234e-02, -8.0113e-02, -6.4620e-04, -7.2014e-02,
         -2.8422e-01,  2.0080e-01, -4.6536e-02,  8.4687e-02, -2.8825e-01,
          7.3836e-02,  1.9851e-01,  3.0218e-01, -7.7665e-02, -1.6358e-02,
         -9.0699e-02,  1.6746e-01,  2.6839e-01, -9.0109e-02,  6.5843e-02,
          1.5158e-01, -2.1982e-01,  1.1848e-01, -6.0693e-02, -3.2397e-01,
          8.1645e-02,  2.5342e-02,  2.1754e-01,  7.8594e-02, -3.3850e-01,
          1.2909e-01, -1.2072e-01,  1.