In this notebook we have implemented the same nural network pipeline but used nn.module, here we have used builtin functions of nn.module

we made the whole model using nn.module,

1.   used loss builtin function
2.   used activation function builtin
3.   used builtin optimizer fucntion

### this made this code very simple and more pytorch oriented

In [42]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [43]:
import torch.nn as nn

In [44]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [45]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [46]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

Train test split

In [47]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

Scaling

In [48]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [49]:
X_train

array([[-0.22030448, -0.51724915, -0.28572222, ..., -0.26929079,
        -0.63695412, -0.44938755],
       [-0.49668311, -0.78444106, -0.52143758, ..., -1.01557376,
        -0.67562393, -1.14203115],
       [-0.56506545, -0.06874844, -0.61086106, ..., -0.97291148,
        -0.03434956, -0.20746192],
       ...,
       [-0.13767582, -1.26156948, -0.11923795, ..., -0.35952611,
         0.26373024, -0.15802494],
       [-1.65946783,  0.36066714, -1.57473907, ..., -0.54536791,
         0.67781947,  3.35673372],
       [-0.42830077, -0.26675673, -0.49712428, ..., -1.50358113,
        -1.07682323, -1.55488249]])

In [50]:
y_train

224    B
189    B
346    B
431    B
321    M
      ..
411    B
301    B
221    B
151    B
360    B
Name: diagnosis, Length: 455, dtype: object

Lable Encoding

In [51]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [52]:
y_train

array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,

numpy arrays to pytorch tensors

In [53]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [54]:
X_train_tensor.shape

torch.Size([455, 30])

In [55]:

y_train_tensor.shape

torch.Size([455])

definig the model

In [57]:
class MySimpleNN(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


important parameter

In [58]:
learning_rate = 0.1
epochs = 25

training pipeline

In [59]:
loss_function = nn.BCELoss()

In [60]:
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor.float())

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1).float())

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.8425496816635132
Epoch: 2, Loss: 0.6164490580558777
Epoch: 3, Loss: 0.49985721707344055
Epoch: 4, Loss: 0.4310205280780792
Epoch: 5, Loss: 0.38480356335639954
Epoch: 6, Loss: 0.35111525654792786
Epoch: 7, Loss: 0.325184166431427
Epoch: 8, Loss: 0.30444052815437317
Epoch: 9, Loss: 0.2873651385307312
Epoch: 10, Loss: 0.27299588918685913
Epoch: 11, Loss: 0.2606905400753021
Epoch: 12, Loss: 0.2500022351741791
Epoch: 13, Loss: 0.24060919880867004
Epoch: 14, Loss: 0.232273131608963
Epoch: 15, Loss: 0.22481313347816467
Epoch: 16, Loss: 0.21808908879756927
Epoch: 17, Loss: 0.21199049055576324
Epoch: 18, Loss: 0.20642884075641632
Epoch: 19, Loss: 0.20133216679096222
Epoch: 20, Loss: 0.19664126634597778
Epoch: 21, Loss: 0.1923070102930069
Epoch: 22, Loss: 0.18828800320625305
Epoch: 23, Loss: 0.18454934656620026
Epoch: 24, Loss: 0.18106107413768768
Epoch: 25, Loss: 0.1777975857257843


In [61]:
model.linear.weight

Parameter containing:
tensor([[ 0.2536,  0.2998,  0.2916,  0.1088,  0.0730,  0.1868,  0.2493,  0.1299,
          0.1498,  0.0802,  0.2379, -0.1299,  0.1165,  0.3308, -0.1623,  0.0846,
          0.0317, -0.0154,  0.0718, -0.1541,  0.1932,  0.2351,  0.2100,  0.2772,
          0.0925,  0.2556,  0.0437,  0.3218,  0.1615, -0.0363]],
       requires_grad=True)

In [62]:
# bias
model.linear.bias

Parameter containing:
tensor([-0.1862], requires_grad=True)

In [63]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor.float())
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5560172200202942
